In [ ]:
import pandas as pd

data = {
    'Age': [18,19,17,18,20,21,19,18,22,20],
    'StudyHours': [12,5,9,15,7,3,11,2,4,14],
    'Score': [85,60,78,90,65,50,82,45,55,88],
    'Gender': ['F','M','F','F','M','M','F','M','F','M']
}

df = pd.DataFrame(data)

In [9]:
df.head(10)

   Age  StudyHours  Score Gender
0    1          12     85      F
1    2           5     60      M
2    3           9     78      F
3    4          15     90      F
4    5           7     65      M
5    6           3     50      M
6    7          11     82      F
7    8           2     45      M
8    9           4     55      F
9   10          14     88      M

In [ ]:
df.describe

            Age  StudyHours      Score
count  10.00000   10.000000  10.000000
mean    5.50000    8.200000  69.800000
std     3.02765    4.685676  16.771669
min     1.00000    2.000000  45.000000
25%     3.25000    4.250000  56.250000
50%     5.50000    8.000000  71.500000
75%     7.75000   11.750000  84.250000
max    10.00000   15.000000  90.000000